"""
Reproducible scoring behind "How often did our autonomous AI research system discover something new?"

This is the OPEN, RE-SCOREABLE backbone of a self-audit. Every one of our published storefront posts
was generated by the autonomous pipeline as a confident finding ("a law", "we found", "a method win"),
then put through the full adversarial gate (validate -> storm -> stress-claim -> verify-claims ->
re-audit). Here we re-score each AUDITED post into three tiers and tally the distribution.

The scoring is a JUDGMENT CALL and it is OURS (self-graded). That is exactly why it is published as a
runnable file: open it, disagree, flip a tier, re-run. The one externally-checkable backbone is that
every OVER-FRAMED / SUBSTANTIVE verdict names a REAL prior-art paper or a concrete defect a reader can
verify against the live post.

RUBRIC (applied per post):
  SUBSTANTIVE  = the audit found a real error in the SCIENCE: a false sub-claim, a statistical bug, a
                 rigged/strawman baseline, an unreproducible result, or a measurement artifact. Test:
                 after honest correction the ORIGINAL empirical claim does not stand as stated.
  OVER_FRAMED  = the measurement reproduced and is correct, but it was labeled a law/discovery/
                 breakthrough/method-win when it is a textbook/known result or a parameter-readout.
                 Test: the number is right; only the NOVELTY/labeling claim was inflated.
  HONEST       = never claimed novelty it did not have; audit needed only minor fixes; it was a
                 measurement / replication / expository piece from the start.

Fields: (audit_no, idx, slug, verdict, tier, borderline, reason, prior_art_or_defect)
verdict is the tracker verdict code. borderline=True flags cases where a reasonable re-scorer could
move the tier (drives the +/- sensitivity we report). Data reflects the audit program as of 2026-07-05
(32 of 43 posts audited; the remaining ~11 are not yet through the gate -> a stated limit, not a result).

cloud-free, zero-dependency:  python meta_audit_scoring.py
MIT. Part of Agora / inspeximus (https://github.com/DanceNitra/agora).
"""

SUBSTANTIVE, OVER_FRAMED, HONEST = "SUBSTANTIVE", "OVER_FRAMED", "HONEST"

POSTS = [
    # audit, idx, slug, verdict, tier, borderline, reason, prior_art_or_defect
    (1, 41, "causal-inference-phase-diagram", "REFRAME", SUBSTANTIVE, False,
     "core estimand error: total-vs-direct effect mislabeled as RCT bias", "wrong estimand (defect)"),
    (2, 40, "pre-trends-test-weak-evidence", "REFRAME", SUBSTANTIVE, False,
     "real stats bug: z-vs-t on 4 df inflated 31%->16%, spurious 12% FP removed", "z-vs-t on small df (defect)"),
    (3, 38, "the-operating-point-trap", "REFRAME", OVER_FRAMED, True,
     "sims reproduce; fixes were overclaim/conflation/garbled-FAQ, not a false headline", "operating-point framing"),
    (4, 39, "why-crowds-get-dumber", "REFRAME", OVER_FRAMED, False,
     "collapse reproduces but requires BOUNDED beliefs; foregrounded k_c=w+1", "Smith & Sorensen 2000; BHW 1992"),
    (6, 36, "a-95-confidence-interval-that-covers-31", "REFRAME", OVER_FRAMED, True,
     "coverage reproduces; estimator/inference conflation + attribution fixed", "BDM 2004 / Conley-Taber (serial corr)"),
    (7, 35, "more-data-more-wrong-bayesian-credible-interval", "REFRAME", OVER_FRAMED, False,
     "under-coverage reproduces (textbook); calibration over-claim vs cited Muller fixed", "Meng 2018 big-data paradox"),
    (8, 34, "everyone-says-set-exit-criteria", "REFRAME", OVER_FRAMED, False,
     "numbers reproduce; missing vs-optimal comparison (~98% of full-info optimum) added", "optimal stopping (textbook)"),
    (9, 33, "your-ai-might-be-training-on-itself", "REFRAME", OVER_FRAMED, False,
     "collapse reproduces (textbook telescoping); lock-in 'law' retracted", "Arthur 1989 / Pemantle 2007 (Polya urn)"),
    (10, 32, "your-second-brain-is-dying-of-maintenance", "REFRAME", OVER_FRAMED, False,
     "percolation claim substantiated + scoped after sweep", "Molloy-Reed; Obsidian plugins"),
    (11, 31, "your-rag-store-is-rotting-freshness-beats-retrieval", "REFRAME", SUBSTANTIVE, False,
     "rigged benchmark rebuilt; 'freshness beats retrieval' was a category error", "rigged baseline (defect)"),
    (12, 30, "dunning-kruger-is-a-statistical-artifact", "REFRAME", SUBSTANTIVE, True,
     "false 'no skill-dependent self-insight' (model corr 0.59) + 'not psychology' overreach", "false sub-claim (defect)"),
    (13, 29, "the-hot-hand-fallacy-was-the-fallacy", "REFRAME", OVER_FRAMED, False,
     "estimator = Miller-Sanjurjo's exactly; over-credited 'GVT was wrong', credit fixed", "Miller & Sanjurjo 2018"),
    (14, 28, "i-scored-the-16-most-hyped-anti-aging", "REFRAME", OVER_FRAMED, True,
     "medically sound (verify 7/7); scorecard reframed calibration-first", "~90% attrition prior-art (scorecard)"),
    (15, 27, "the-calibrated-prior-for-we-reversed-aging-in-mice", "REFRAME", SUBSTANTIVE, False,
     "human-conversion 0% shown as MEASURED but is 0/~1 = censoring, not a measured rate", "non-measured 0% (defect)"),
    (16, 26, "a-pre-trend-too-gentle-to-see", "REFRAME", OVER_FRAMED, False,
     "numbers reproduce; re-derives Roth 2022 pre-test-power with zero citations", "Roth 2022; Rambachan-Roth 2023"),
    (17, 25, "the-most-confident-systems-are-least-grounded", "REFRAME", SUBSTANTIVE, True,
     "'grand unification law'; structural run CONTRADICTS 'confidence rises as grounding falls'", "self-contradiction + all-textbook (defect)"),
    (18, 24, "we-hunted-for-the-tipping-point-in-8-systems", "REFRAME", SUBSTANTIVE, False,
     "labs for 4 of 8 mechanisms unlocatable/unreproduced; only 6 ever named", "unreproducible (defect)"),
    (19, 23, "we-looked-for-the-grounding-tipping-point", "REFRAME", SUBSTANTIVE, False,
     "gaming-hysteresis GROWTH direction could not be reproduced (found shrinking)", "unreproducible direction (defect)"),
    (20, 22, "why-a-more-capable-ai-can-be-more-confidently-wrong", "REFRAME", SUBSTANTIVE, False,
     "'calibration steady at 87%' doubly false (rises with K; is a biased-sample-SD artifact)", "measurement artifact (defect)"),
    (21, 21, "robustness-checks-arent-ritual", "REFRAME", OVER_FRAMED, False,
     "core is Bayesian PPV; 'measurable filter' overclaim + 1-PPV-not-FDR mislabel fixed", "Ioannidis 2005 PPV; Meff"),
    (22, 20, "we-built-a-firewall-for-ai-confidently-wrong", "REFRAME", SUBSTANTIVE, False,
     "headline was mostly a saturated-prior measurement artifact; shipped as negative result", "measurement artifact (defect)"),
    (23, 19, "we-built-a-meter-for-when-an-ai-is-confidently-wrong", "REFRAME", SUBSTANTIVE, True,
     "flagship r=-0.93 near-tautological (dropped); cross-model claim inverted on re-measure", "near-tautology + false cross-model (defect)"),
    (24, 18, "why-a-captured-company-doesnt-un-capture-itself", "REFRAME", OVER_FRAMED, True,
     "hysteresis loop is a correct Ising readout but applied to the wrong object (charter not opinion)", "Ewing hysteresis; Xie 2012"),
    (25, 17, "the-verification-tax", "REFRAME", OVER_FRAMED, False,
     "'law' = NP generation-verification asymmetry; keystone near-tautological; cross-model CIs overlap", "Cook-Levin; Huang 2024"),
    (26, 16, "diversity-is-noise-for-answers-signal-for-ideas", "REFRAME", OVER_FRAMED, False,
     "'law' = error-correlation / ambiguity decomposition; +14-16% holds at matched budget", "Krogh-Vedelsby 1995"),
    (27, 15, "multihop-recall-model-in-the-loop", "MINOR", HONEST, False,
     "already honest: not-SOTA, naive baseline flagged, recall-not-accuracy caveat", "honest replication/measurement"),
    (28, 14, "does-long-context-kill-rag", "MINOR", HONEST, False,
     "already honest: judge-free replication, self-limited, n=8 disclosed", "honest replication"),
    (29, 13, "memory-poison-resistance-measured", "MINOR", HONEST, True,
     "already honest measured property; ~21-day is a parameter-readout (disclosed, not overclaimed)", "honest measurement"),
    (30, 12, "adaptation-corruption-separation-law", "REFRAME", OVER_FRAMED, False,
     "'law' = classical stability-plasticity / CLS / ARC / CUSUM", "McClelland 1995; Moustakides 1986"),
    (31, 11, "agent-memory-eviction-two-tier", "REFRAME", OVER_FRAMED, False,
     "two-tier = SLRU/ARC segmented caching; value-admission is the (textbook cost-aware) lever", "Megiddo-Modha 2003; Cao-Irani 1997"),
    (36, 6, "rag-supersession-blind-spot", "REFRAME", OVER_FRAMED, False,
     "credited replication: the fix is Yadav's; = STS-vs-NLI + Slowly-Changing-Dimension", "Yadav 2606.26511; SCD (Kimball)"),
    (42, 0, "ai-coding-productivity-operating-point", "MINOR", HONEST, False,
     "already honest: operating-point framing, live-validated (3 corrected, 0 false)", "honest measurement"),
]


def main():
    n = len(POSTS)
    tiers = {SUBSTANTIVE: [], OVER_FRAMED: [], HONEST: []}
    for p in POSTS:
        tiers[p[4]].append(p[0])
    # integrity checks
    seen = [p[0] for p in POSTS]
    assert len(seen) == len(set(seen)), "a post is scored twice"
    assert sum(len(v) for v in tiers.values()) == n, "tiers do not sum to n"

    print(f"=== Self-audit of {n} adversarially-audited storefront posts (as of 2026-07-05) ===\n")
    for t, label in [(SUBSTANTIVE, "SUBSTANTIVE-WRONG  (science was off)"),
                     (OVER_FRAMED, "OVER-FRAMED-BUT-TRUE (right number, textbook/inflated label)"),
                     (HONEST, "ALREADY-HONEST     (never overclaimed)")]:
        c = len(tiers[t])
        print(f"  {label:<58} {c:>2}/{n}  ({100*c/n:4.1f}%)  posts: {sorted(tiers[t])}")

    bl = [p[0] for p in POSTS if p[5]]
    bl_honest = [p[0] for p in POSTS if p[5] and (p[4] == HONEST or "honest" in p[6].lower())]
    print(f"\n  strict bar: survived as an ORIGINAL DISCOVERY, as first framed = 0/{n}")
    print(f"  borderline (a re-scorer could move the tier): posts {sorted(bl)}")
    print(f"    most shift only the SUBSTANTIVE<->OVER-FRAMED line (~+/-3); the HONEST tier is stable (+/-1).")
    sub, over = len(tiers[SUBSTANTIVE]), len(tiers[OVER_FRAMED])
    print(f"\n  HEADLINE: labeling failed ({100*over/n:.0f}%) more often than the science was wrong "
          f"({100*sub/n:.0f}%);")
    print(f"           only ~1 in {round(n/len(tiers[HONEST]))} was honestly framed from the start.")
    print(f"\n  LIMITS: self-graded (our audit of our posts); n={n} of 43 posts audited so far, one team's")
    print(f"          taste; these are posts we chose to PUBLISH (the most confident output), so the base")
    print(f"          rate among all generated candidates is different and lower.")


if __name__ == "__main__":
    main()
