#!/usr/bin/env python3
"""
Agora — Mind Digest. A shareable, self-contained status snapshot of Agora's mind.

Built by Agora's Hands (the Action Engine): reads Agora's own state files and prints a digest of its
predictions, the lessons it has learned, and whether it holds a worldview. No dependencies, read-only.
"""
import json
import pathlib
import re

SERVER = pathlib.Path(__file__).resolve().parent.parent / "server"


def _load_json(name):
    try:
        return json.loads((SERVER / name).read_text(encoding="utf-8"))
    except Exception:
        return None


def main():
    bar = "=" * 56
    print(bar)
    print("   A G O R A   —   M I N D   D I G E S T")
    print(bar)

    preds = _load_json(".predictions.json") or []
    done = [p for p in preds if p.get("status") in ("correct", "incorrect")]
    correct = sum(1 for p in done if p["status"] == "correct")
    rate = f"{correct}/{len(done)} ({correct / len(done):.0%})" if done else "no calls resolved yet"
    print(f"\nPREDICTIONS  —  {len(preds)} made, track record {rate}")
    for p in preds[-6:]:
        mark = {"correct": "OK ", "incorrect": "X  ", "pending": "...."}.get(p.get("status"), "?")
        print(f"  [{mark}] {p['direction']:<4} {p.get('metric_label',''):<14} {p['theme'][:30]:<30} "
              f"({p['confidence']:.0%})")

    lessons = (_load_json(".lessons.json") or {}).get("lessons", [])
    print(f"\nLESSONS LEARNED  —  {len(lessons)}")
    for lesson in lessons[:4]:
        print(f"  - {lesson[:80]}")

    try:
        wv = (SERVER / ".worldview.md").read_text(encoding="utf-8")
        m = re.search(r"^>\s*(.+)$", wv, re.MULTILINE)
        head = re.sub(r"\s+", " ", m.group(1))[:90] if m else f"{len(wv)} chars"
        print(f"\nWORLDVIEW  —  present\n  {head}")
    except Exception:
        print("\nWORLDVIEW  —  not yet synthesized")

    print("\n" + bar)
    print("  generated by Agora's Hands — knowledge that acts")
    print(bar)


if __name__ == "__main__":
    main()
