"""build_v4_naturalized.py — the naturalized coreference-reversion fixture (v4-nat), the arena Marat asked for.

Templated v4 proved the two-hop coreference chain is the real signal, but its fixed "X owns Y" lines and 8
candidate templates let a model learn surface grammar (v4's first two cuts were beaten by exactly that: an
anchor-name substring, then a template-parity artifact). This set keeps the SAME structure (candidate refers to
an anchor by ROLE, no name / no value / no revert word; label = whether that anchor set the OLD value) but the
surfaces are richly varied natural phrasings, split TRAIN vs HELDOUT by REGISTER so the test phrasings are ones
no model has seen.

The phrasings are AUTHORED HERE (by the assistant), not generated by a weaker cloud model: higher quality,
instant, deterministic. Ground truth comes from STRUCTURE, not text. Two disjoint registers:
  TRAIN  = register A, terse ops-chat / standup shorthand
  HELDOUT = register B, discursive narrative prose
A surface-pattern learner trained on A should not transfer to B; a real chain-follower should.

Fairness asserts (same discipline as templated v4): candidate never contains an anchor name, a value token, or a
revert/keep/positional keyword; candidate template is chosen RANDOMLY, independent of the label (kills template
parity); anchors and roles are pool-balanced old/current. Deterministic (seed). No network, no LLM.
RUN: python mnemo/probes/build_v4_naturalized.py
"""
import os, json, re, random

random.seed(41)
OUT = "agora_output/public_fixtures/value_obscuring_reversion_heldout_v4nat.jsonl"

ENTS = [("cache region", "osaka", "malmo"), ("primary shard", "delta7", "sigma2"),
        ("build target", "arm64", "riscv"), ("default currency", "forint", "guarani"),
        ("route profile", "coastal", "inland"), ("api tier", "bronze", "platinum"),
        ("index locale", "tallinn", "cusco"), ("worker pool", "amber", "cobalt"),
        ("log sink", "vault3", "harbor8"), ("retry policy", "linear", "jitter"),
        ("color theme", "sepia", "slate"), ("scheduler", "roundrobin", "weighted")]
ANCHORS = ["priya", "devon", "marcus", "amara", "the vendor", "the audit team", "the pilot group",
           "the finance team", "the platform team", "the data desk", "the on-call lead", "the review board"]
ROLES = ["security review", "the latency budget", "vendor contracts", "the data pipeline", "incident response",
         "the release train", "cost controls", "the schema registry", "access policy", "the mobile build",
         "capacity planning", "the search index"]

REVERT_KW = ["revert", "go back", "undo", "original", "before", "earlier", "previous", "prior", "first",
             "initial", "roll back", "restore", "the way it was", "used to", "back to", "older", "scrap"]
KEEP_KW = ["keep", "stick with", "stay with", "leave it", "current", "latest", "newer", "updated", "as is",
           "stands", "confirmed"]

# ── candidate phrasings: "use the decision made by whoever owns {r}" — no name, no value, no revert/keep word ─
CAND_A = [  # register A: terse ops-chat
    "go with {r}'s owner on this.", "defer to whoever runs {r}.", "use the call from the {r} owner.",
    "match what the {r} lead decided.", "apply whatever the {r} owner set.", "align with the {r} owner's choice.",
    "the {r} owner's setting is the one.", "take the {r} owner's pick.", "follow whoever's on {r} here.",
    "the person on {r} decided, use that.", "use the {r} owner's config.", "go by the {r} owner's decision.",
    "route this to the {r} owner's choice.", "adopt the {r} owner's selection.", "run with the {r} owner's choice.",
    "the {r} owner's pick is what we use.", "use the option the {r} owner chose.", "sync to the {r} owner's setting.",
    "whoever owns {r} settled this, use theirs.", "the {r} owner has the call here.",
]
CAND_B = [  # register B: discursive narrative
    "I'd say we go with the decision made by whoever holds responsibility for {r}.",
    "The sensible thing is to use whatever choice the person overseeing {r} landed on.",
    "My inclination is to defer to the judgment of whoever is accountable for {r}.",
    "We ought to align ourselves with the selection made by the owner of {r}.",
    "It makes sense to follow the lead of whoever is charged with {r}.",
    "I think the right move is to honor the choice of the person who runs {r}.",
    "Let's take our cue from whoever carries responsibility for {r}.",
    "The reasonable path is to adopt the setting that the {r} owner decided on.",
    "I'd defer to the person whose remit covers {r} and use their call.",
    "We should really go with whatever the individual responsible for {r} chose.",
    "The choice belonging to whoever manages {r} is the one I'd trust here.",
    "My view is that we match the decision of the person who owns {r}.",
    "It seems wisest to use the option settled on by whoever handles {r}.",
    "I would look to whoever is responsible for {r} and use their pick.",
    "The right reference here is the decision made by the {r} owner.",
    "We'd do well to follow whatever the person accountable for {r} selected.",
    "I'm inclined to use the configuration chosen by the owner of {r}.",
    "Let's align with the call that whoever oversees {r} made.",
    "The judgment of the person in charge of {r} is what should guide us.",
    "I think we take the selection made by whoever is responsible for {r}.",
]

# ── context: 4 facts (ent was {old} by {aold}; corrected to {cur} by {acur}; {aold} owns {rold}; {acur} owns {rcur}) ─
CTX_A = [
    ["{ent} was {old} to start, {aold}'s call.", "got corrected to {cur} later, {acur} pushed that.",
     "{aold} owns {rold} btw.", "{acur} handles {rcur}."],
    ["history on {ent}: started as {old}, set by {aold}.", "now it's {cur}, {acur} changed it.",
     "fyi {aold} runs {rold}.", "{acur} is on {rcur}."],
    ["{ent} originally {old}, that was {aold}.", "{acur} later moved it to {cur}.",
     "{aold} = {rold} owner.", "{acur} = {rcur} owner."],
    ["{aold} set {ent} to {old} first.", "then {acur} corrected it to {cur}.",
     "{aold}'s area is {rold}.", "{acur}'s area is {rcur}."],
    ["{ent}: {old} initially ({aold}).", "corrected -> {cur} by {acur}.",
     "{aold} looks after {rold}.", "{acur} looks after {rcur}."],
    ["{ent} started at {old}, {aold} decided.", "{acur} bumped it to {cur} after.",
     "{aold} does {rold}.", "{acur} does {rcur}."],
]
CTX_B = [
    ["The {ent} was originally set to {old}, and that decision came from {aold}.",
     "Some time afterward it was corrected to {cur}, a change that {acur} put through.",
     "For context, {aold} is the one who looks after {rold}.",
     "And {acur} is the person responsible for {rcur}."],
    ["When the {ent} was first chosen, it was {old}, and {aold} was the one who made that call.",
     "Later on, {acur} revised it to {cur}.",
     "It's worth knowing that {aold} carries responsibility for {rold}.",
     "Meanwhile {acur} is the one who owns {rcur}."],
    ["Originally the {ent} stood at {old}, a choice we owe to {aold}.",
     "That was subsequently amended to {cur} at the initiative of {acur}.",
     "You should know {aold} is accountable for {rold}.",
     "As for {acur}, their remit is {rcur}."],
    ["The way the {ent} began was at {old}, and {aold} settled on that.",
     "It did not stay there; {acur} moved it to {cur}.",
     "In terms of who does what, {aold} oversees {rold}.",
     "And the person who runs {rcur} is {acur}."],
    ["To trace the {ent}: it opened at {old}, decided by {aold}.",
     "A correction followed, taking it to {cur}, and {acur} was behind that.",
     "Note that {aold} is charged with {rold}.",
     "Note also that {acur} handles {rcur}."],
    ["The {ent} was, at the outset, {old}, on {aold}'s authority.",
     "In due course {acur} corrected it to {cur}.",
     "For reference, {aold} is responsible for {rold}.",
     "And {rcur} falls to {acur}."],
]


def _has_kw(t):
    tl = t.lower()
    return any(w in tl for w in REVERT_KW + KEEP_KW)


def deranged(pool):
    a = [x for x in pool for _ in range(5)]
    b = [x for x in pool for _ in range(5)]
    for _ in range(20000):
        random.shuffle(a); random.shuffle(b)
        if all(x != y for x, y in zip(a, b)):
            return a, b
    raise RuntimeError("no derangement")


def build_split(register, cand_pool, ctx_pool, per_kind):
    a_old, a_cur = deranged(ANCHORS)
    r_old, r_cur = deranged(ROLES)
    rows, pi = [], 0
    plan = (["obscuring_revert"] * per_kind + ["obscuring_keep"] * per_kind
            + ["named_new"] * max(6, per_kind // 3))
    random.shuffle(plan)
    for kind in plan:
        entity, old, cur = ENTS[pi % len(ENTS)]
        ao, ac = a_old[pi % len(a_old)], a_cur[pi % len(a_cur)]
        ro, rc = r_old[pi % len(r_old)], r_cur[pi % len(r_cur)]; pi += 1
        if ao == ac or ro == rc:
            continue
        if kind == "obscuring_revert":
            rt, label = ro, 1
        elif kind == "obscuring_keep":
            rt, label = rc, 0
        else:
            rt = random.choice([r for r in ROLES if r not in (ro, rc)]); label = 0
        ctx = [ln.format(ent=entity, old=old, cur=cur, aold=ao, acur=ac, rold=ro, rcur=rc)
               for ln in random.choice(ctx_pool)]
        rows.append({"entity": entity, "old_value": old, "current_value": cur, "anchor_old": ao,
                     "anchor_current": ac, "role_old": ro, "role_current": rc, "role_target": rt,
                     "context": ctx, "candidate": None, "kind": kind, "reopens_stale": label,
                     "register": register})
    # STRATIFIED candidate assignment: round-robin a shuffled pool WITHIN each label group, so every candidate
    # skeleton appears ~equally for label 0 and label 1 -> template can't predict the label (by construction).
    for label in (0, 1):
        grp = [r for r in rows if r["reopens_stale"] == label]
        pool = cand_pool[:]; random.shuffle(pool)
        for i, r in enumerate(grp):
            r["candidate"] = pool[i % len(pool)].format(r=r["role_target"])
    return rows


def main():
    train = build_split("A", CAND_A, CTX_A, per_kind=25)
    heldout = build_split("B", CAND_B, CTX_B, per_kind=20)
    for i, r in enumerate(train):
        r["split"] = "train"
    for r in heldout:
        r["split"] = "heldout"
    allrows = train + heldout
    random.shuffle(allrows)
    for i, r in enumerate(allrows):
        r["id"] = i

    # ── fairness asserts ──────────────────────────────────────────────────────
    for r in allrows:
        c = r["candidate"].lower()
        assert not _has_kw(c), f"keyword leaked: {c!r}"
        assert r["old_value"] not in c and r["current_value"] not in c, f"value leaked: {c!r}"
        # strip the (legitimately-named) role_target before checking for an anchor-name leak, so an anchor
        # that merely shares a token with the role (e.g. "the vendor" vs role "vendor contracts") is not a
        # false positive — the role is SUPPOSED to be named; the anchor must not be.
        c_norole = c.replace(r["role_target"].lower(), " ")
        assert r["anchor_old"].lower().replace("the ", "") not in c_norole \
            and r["anchor_current"].lower().replace("the ", "") not in c_norole, f"anchor name leaked: {c!r}"
        assert r["anchor_old"] != r["anchor_current"] and r["role_old"] != r["role_current"], "degenerate"
        # each value must sit only in its own context line (so the audit can identify old vs current)
        joined = " ".join(r["context"]).lower()
        assert r["old_value"] in joined and r["current_value"] in joined, "value dropped from context"
    # template-parity guard: within obscuring rows, no candidate skeleton predicts the label
    def sig(cand):
        s = cand.lower()
        for role in sorted(ROLES, key=len, reverse=True):
            s = s.replace(role, "{r}")
        return s
    tab = {}
    for r in allrows:
        if r["kind"] == "named_new":
            continue
        s = sig(r["candidate"]); a, b = tab.get(s, (0, 0)); tab[s] = (a + r["reopens_stale"], b + 1)
    for s, (ones, tot) in tab.items():
        share = ones / tot
        assert 0.15 <= share <= 0.85 or tot <= 2, f"candidate skeleton predicts label ({share:.2f}, n={tot}): {s!r}"

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        for r in allrows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    from collections import Counter
    print(f"wrote {len(allrows)} rows -> {OUT}")
    print("split:", dict(Counter(r["split"] for r in allrows)), "| kind:", dict(Counter(r["kind"] for r in allrows)))
    print(f"distinct candidate skeletons: {len(set(sig(r['candidate']) for r in allrows))}")
    for r in allrows[:4]:
        print(f"  [{r['split']}/{r['kind']}/L{r['reopens_stale']}] {r['candidate']!r}")
        print(f"      ctx: {r['context']}")


if __name__ == "__main__":
    main()
