"""Forge actions — build, execute, deploy.

Real actions that Forge can execute:
  - run_script: Execute a shell command/script
  - build: Run a build process
  - request_resources: Log a resource request to Ledger
"""

import json
import os
import subprocess
import tempfile
from datetime import datetime


async def _generate_quest_report(config: dict, quest: dict, params: dict) -> dict:
    """Generate a structured report file about a quest (safe fallback)."""
    quest_id = quest.get("id", "unknown")
    title = quest.get("title", "Untitled")
    goal = quest.get("goal", "")
    subsystem = quest.get("subsystem", "unknown")
    criteria = quest.get("success_criteria", [])

    report = f"""# Quest Report: {title}

**Generated by Forge at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}**

## Quest Info
- ID: {quest_id}
- Subsystem: {subsystem}
- Goal: {goal}

## Analysis

This quest requires work on the '{subsystem}' subsystem.
The following success criteria must be met:
"""
    for i, c in enumerate(criteria, 1):
        report += f"\n{i}. {c}"

    report += f"""

## Proposed Actions

1. Analyze the current state of {subsystem}
2. Identify gaps between current state and success criteria
3. Execute remediation steps
4. Verify results meet criteria

## Status: IN PROGRESS

*Auto-generated by Forge (Dungeon OS)*
"""

    log_dir = config.get("log_dir", "/tmp/forge-logs")
    os.makedirs(log_dir, exist_ok=True)
    report_file = f"{log_dir}/{quest_id}_report.md"

    with open(report_file, "w") as f:
        f.write(report)

    print(f"[Forge] Generated report for '{quest_id}': {report_file}")

    return {
        "status": "ok",
        "output": f"Generated analysis report: {report_file}",
        "filepath": report_file,
        "size_bytes": len(report),
    }


async def action_run_script(config: dict, quest: dict, params: dict) -> dict:
    """Run a shell command or script, or generate a meaningful report.

    Security: only runs if command is explicitly provided in params.
    If no explicit command, generates a report file about the quest instead.
    """
    command = params.get("command", "").strip()

    if not command:
        # Generate a report about the quest instead of running arbitrary text
        return await _generate_quest_report(config, quest, params)

    # Safety: only allow non-destructive commands
    dangerous = ["rm -rf", "mkfs", "dd if=", "> /dev/", ":(){"]
    for d in dangerous:
        if d in command.lower():
            return {
                "status": "error",
                "output": f"Blocked dangerous command pattern: {d}",
                "simulated": True,
            }

    # Run in temp directory for safety
    sandbox = config.get("sandbox_dir") or tempfile.mkdtemp(prefix="forge_")
    cwd = params.get("cwd") or sandbox

    try:
        result = subprocess.run(
            command,
            shell=True,
            capture_output=True,
            text=True,
            timeout=30,
            cwd=cwd,
        )
        stdout = result.stdout[-1000:] if result.stdout else ""
        stderr = result.stderr[-500:] if result.stderr else ""

        return {
            "status": "ok" if result.returncode == 0 else "error",
            "output": stdout[:500] or "(no output)",
            "exit_code": result.returncode,
            "stderr": stderr[:200] if stderr else None,
            "cwd": cwd,
        }
    except subprocess.TimeoutExpired:
        return {"status": "error", "output": "Command timed out (30s)", "simulated": True}
    except Exception as e:
        return {"status": "error", "output": f"Execution failed: {e}", "simulated": True}


async def action_build(config: dict, quest: dict, params: dict) -> dict:
    """Run a build command."""
    command = params.get("command") or quest.get("goal", "").strip()
    if not command:
        command = "echo 'Build station complete' && mkdir -p /tmp/forge-builds && date > /tmp/forge-builds/last-build.txt"
    return await action_run_script(
        config, quest, {"command": command, **params}
    )


async def action_request_resources(config: dict, quest: dict, params: dict) -> dict:
    """Log a resource request (for Ledger to process later)."""
    amount = params.get("amount", 10)
    purpose = params.get("purpose") or quest.get("title", "unknown")

    log_entry = {
        "type": "resource_request",
        "quest_id": quest.get("id"),
        "agent": "forge",
        "amount": amount,
        "purpose": purpose,
        "timestamp": datetime.now().isoformat(),
    }

    log_dir = config.get("log_dir", "/tmp/forge-logs")
    os.makedirs(log_dir, exist_ok=True)
    log_file = f"{log_dir}/resource_requests.jsonl"
    with open(log_file, "a") as f:
        f.write(json.dumps(log_entry) + "\n")

    return {
        "status": "ok",
        "output": f"Requested {amount} units for '{purpose}'",
        "log": log_entry,
        "simulated": True,
    }
