"""Forge actions — build, execute, deploy.

Real actions that Forge can execute:
  - run_script: Execute a shell command/script
  - build: Run a build process
  - request_resources: Log a resource request to Ledger
"""

import json
import os
import subprocess
import tempfile
from datetime import datetime


async def _generate_quest_report(config: dict, quest: dict, params: dict) -> dict:
    """Generate a structured report file about a quest (safe fallback)."""
    quest_id = quest.get("id", "unknown")
    title = quest.get("title", "Untitled")
    goal = quest.get("goal", "")
    subsystem = quest.get("subsystem", "unknown")
    criteria = quest.get("success_criteria", [])

    report = f"""# Quest Report: {title}

**Generated by Forge at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}**

## Quest Info
- ID: {quest_id}
- Subsystem: {subsystem}
- Goal: {goal}

## Analysis

This quest requires work on the '{subsystem}' subsystem.
The following success criteria must be met:
"""
    for i, c in enumerate(criteria, 1):
        report += f"\n{i}. {c}"

    report += f"""

## Proposed Actions

1. Analyze the current state of {subsystem}
2. Identify gaps between current state and success criteria
3. Execute remediation steps
4. Verify results meet criteria

## Status: IN PROGRESS

*Auto-generated by Forge (Dungeon OS)*
"""

    log_dir = config.get("log_dir", "/tmp/forge-logs")
    os.makedirs(log_dir, exist_ok=True)
    report_file = f"{log_dir}/{quest_id}_report.md"

    with open(report_file, "w") as f:
        f.write(report)

    print(f"[Forge] Generated report for '{quest_id}': {report_file}")

    return {
        "status": "ok",
        "output": f"Generated analysis report: {report_file}",
        "filepath": report_file,
        "size_bytes": len(report),
    }


# REMOVED 2026-08-14: `action_run_script` and `action_build`.
#
# action_run_script executed subprocess.run(command, shell=True) behind a denylist of five
# substrings (rm -rf, mkfs, dd if=, > /dev/, :(){), which "rm  -rf", "curl x | sh" or
# "powershell -e <b64>" walk straight past, and it took cwd from the caller. action_build fed it
#     command = params.get("command") or quest.get("goal", "").strip()
# -- a research goal, built by agent_worker from a paper claim or a GitHub scan finding. A quest
# goal is prose; it is never a command.
#
# Both were registered and neither was reachable: the nine registry.execute call sites all pass
# string literals and none names "forge", and the `*:<skill>` wildcard resolves to `*:run_script`,
# which was never registered (only *:wait and *:move are). POST /{npc_name}/action takes a
# free-form npc name but a CLOSED action set, and lands in RealActionEngine, not here.
#
# Deleted rather than hardened because the capability already exists, done correctly:
# real_action_engine._run_script uses shlex.split, shell=False, a metacharacter rejection and a
# 21-command read-only allowlist. Keeping a shell=True denylist beside it is a landmine, not a
# spare tire -- one line in registry.py would have made it live with untrusted input on day one.

async def action_request_resources(config: dict, quest: dict, params: dict) -> dict:
    """Log a resource request (for Ledger to process later)."""
    amount = params.get("amount", 10)
    purpose = params.get("purpose") or quest.get("title", "unknown")

    log_entry = {
        "type": "resource_request",
        "quest_id": quest.get("id"),
        "agent": "forge",
        "amount": amount,
        "purpose": purpose,
        "timestamp": datetime.now().isoformat(),
    }

    log_dir = config.get("log_dir", "/tmp/forge-logs")
    os.makedirs(log_dir, exist_ok=True)
    log_file = f"{log_dir}/resource_requests.jsonl"
    with open(log_file, "a") as f:
        f.write(json.dumps(log_entry) + "\n")

    return {
        "status": "ok",
        "output": f"Requested {amount} units for '{purpose}'",
        "log": log_entry,
        "simulated": True,
    }
