"""Scribe actions — knowledge management, vault operations.

Real actions that Scribe can execute:
  - write_note: Write content to Obsidian vault
  - summarize: Compress multiple entries
  - query: Search the vault for information
"""

import json
import os
from datetime import datetime
from pathlib import Path


async def action_write_note(config: dict, quest: dict, params: dict) -> dict:
    """Write a note to the Obsidian vault (or fallback directory).

    Uses:
      - config['vault_path'] or $OBSIDIAN_VAULT_PATH
      - Falls back to ~/Obsidian Vault/ or ~/vault/
    """
    vault_path = (
        config.get("vault_path")
        or os.getenv("OBSIDIAN_VAULT_PATH")
        or os.path.expanduser("~/Obsidian Vault")
        or os.path.expanduser("~/vault")
    )

    title = params.get("title") or quest.get("title", "Untitled")
    body = params.get("body") or quest.get("goal", "")
    tags = params.get("tags", ["dungeon-os", "auto-generated"])
    subsystem = quest.get("subsystem", "knowledge")

    # Build frontmatter + content
    frontmatter = {
        "title": title,
        "created": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "source": f"quest:{quest.get('id', 'unknown')}",
        "subsystem": subsystem,
        "tags": tags,
        "status": "auto-generated",
    }

    content = f"""---
{json.dumps(frontmatter, indent=2)}
---

# {title}

*Generated by Scribe (Dungeon OS) on {datetime.now().strftime('%Y-%m-%d %H:%M')}*

## Summary

{body}

## Quest Context

- **Quest ID:** {quest.get('id', 'unknown')}
- **Goal:** {quest.get('goal', '')}
- **Reward:** {quest.get('reward', 0)} pts

## Details

{params.get('details', '')}

---

*This note was autonomously created by Scribe as part of the Dungeon OS quest system.*
"""

    # Write to vault
    vault = Path(vault_path)
    vault.mkdir(parents=True, exist_ok=True)

    # Clean filename
    safe_title = "".join(c if c.isalnum() or c in " -_" else "_" for c in title)[:60]
    filename = f"{datetime.now().strftime('%Y%m%d_%H%M')}_{safe_title}.md"
    filepath = vault / filename

    filepath.write_text(content)

    return {
        "status": "ok",
        "output": f"Written to {filepath} ({len(content)} bytes)",
        "filepath": str(filepath),
        "size_bytes": len(content),
    }


async def action_query(config: dict, quest: dict, params: dict) -> dict:
    """Query the vault for information (simulated search)."""
    vault_path = (
        config.get("vault_path")
        or os.getenv("OBSIDIAN_VAULT_PATH")
        or os.path.expanduser("~/Obsidian Vault")
    )
    query = params.get("query") or quest.get("goal", "")[:50]

    vault = Path(vault_path)
    results = []

    if vault.exists():
        for md_file in vault.glob("*.md"):
            if query.lower() in md_file.stem.lower():
                results.append(md_file.stem)
            elif md_file.exists():
                try:
                    text = md_file.read_text()[:200]
                    if query.lower() in text.lower():
                        results.append(md_file.stem)
                except Exception:
                    pass

    return {
        "status": "ok",
        "output": f"Found {len(results)} results for '{query[:30]}'",
        "results": results[:10],
        "total_found": len(results),
    }


async def action_summarize(config: dict, quest: dict, params: dict) -> dict:
    """Summarize content — delegates to write_note with compressed output."""
    sources = params.get("sources", [])
    if not sources:
        return {"status": "skipped", "output": "No sources to summarize", "simulated": True}

    summary_body = f"Summary of {len(sources)} sources:\n\n"
    for s in sources[:5]:
        summary_body += f"- {s}\n"

    return await action_write_note(
        config,
        quest,
        {
            "title": f"Summary: {quest.get('title', 'Untitled')}",
            "body": summary_body,
            "tags": ["summary", "auto-generated"],
            "details": json.dumps({"sources": sources, "count": len(sources)}),
        },
    )
