"""The swarm must gate on ONE board, and it was gating on two that disagreed on 41 terms.

There are two legitimate halves of the vocabulary:

* the LIVE half, derived by `methods.board_priority_terms` from the board text the owner actually
  set — this is what he says today, and it changes when he changes it;
* the CURATED half, a set literal in `mcp_server._BOARD_CORE` — technical terms and competitor names
  ("supersede", "provenance", "locomo", "graphiti") that prose cannot express as single words.

They were maintained separately and drifted. Measured 2026-07-31: the curated half was missing
`agent`, `integrity`, `moat`, `quality`, `correction`, `product`, `resistance` and ten more, so
Sergeant Voss's organ — which parses that literal with `ast`, deliberately, because it must not
import `mcp_server` (it is `__main__` and importing it starts a second server) — admitted **1 of his
8 challenge targets where the live half admitted 3**. He was refusing real work: "self-refinement
plateaus at the critic's competence ceiling" and "winner-take-all reinforcement becomes
quality-blind" are exactly what a Quality Assurance organ exists to attack.

The literal cannot be replaced by a fetch without breaking that static read, so the drift is guarded
here instead of by discipline.
"""
from __future__ import annotations

import ast
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
MCP = REPO / "agora-game-server" / "mcp_server.py"
sys.path.insert(0, str(REPO / "server"))


def literal(name: str) -> set:
    tree = ast.parse(MCP.read_text(encoding="utf-8", errors="replace"))
    for node in tree.body:
        if isinstance(node, ast.Assign):
            if name in {t.id for t in node.targets if isinstance(t, ast.Name)}:
                return set(ast.literal_eval(node.value))
    raise AssertionError("%s is not a module-level literal in mcp_server.py any more -- "
                         "guard_l._board_vocabulary parses it statically and would read empty, "
                         "which makes its gate pass everything" % name)


def live_terms() -> set:
    from agora.execution.board import priorities_text
    from agora.execution.methods import board_priority_terms
    return board_priority_terms(priorities_text())


def test_both_literals_parse_and_are_non_empty():
    """A gate that resolves to the empty set reports safe on everything."""
    core, banned = literal("_BOARD_CORE"), literal("_BOARD_BANNED")
    assert len(core) >= 30, "_BOARD_CORE shrank to %d terms" % len(core)
    assert len(banned) >= 10, "_BOARD_BANNED shrank to %d terms" % len(banned)


def test_the_curated_literal_covers_the_live_board():
    """The drift that cost Voss two thirds of his workable targets."""
    from agora.execution.methods import light_stem, _gerunds
    # Compare STEMMED to STEMMED. `live` comes from `board_priority_terms`, which stems; the literal
    # is hand-written in natural form ("compounds", "memories"). Comparing the two raw reported
    # `compound` and `operation` as "missing" while the literal plainly contains them -- a drift
    # report generated by the comparison rather than by any drift.
    #
    # AND EXPAND BOTH SIDES, for the same reason one layer on. `board_priority_terms` also adds a
    # gerund for every term, so the live set carries `erasureing`, `provableing`, `inspeximusing`
    # and `mem0ing`: forms no human wrote and the curated literal will never contain. Stemming was
    # made symmetric and this was not, so the test reported 29 missing terms, every one of them
    # manufactured by the comparison. Expanding the literal the same way takes it to 0, which is
    # the measurement that says there is no drift here rather than the assertion that there is.
    live = {light_stem(w) for w in live_terms()}
    core = {light_stem(w) for w in literal("_BOARD_CORE")}
    core |= {g for t in core for g in _gerunds(t)}
    if not live:
        import pytest
        pytest.skip("no board is set on this machine")
    missing = sorted(live - core)
    assert not missing, (
        "the live board names %d term(s) the dungeon's literal does not: %s. Any organ parsing "
        "_BOARD_CORE will refuse work the board asks for." % (len(missing), missing))


def test_the_two_halves_do_not_contradict_each_other():
    """A term cannot be both what we prioritise and what we refuse."""
    core, banned = literal("_BOARD_CORE"), literal("_BOARD_BANNED")
    clash = sorted(core & banned)
    assert not clash, "these terms are both core and banned: %s" % clash


def test_the_banned_list_still_refuses_the_deprioritised_subjects():
    """The control. A `_BOARD_CORE` widened until it admits everything would pass the test above and
    silently undo the polarity fix, so the refusals must still bite."""
    banned = literal("_BOARD_BANNED")
    for w in ("physics", "finance", "health", "politics", "trivia", "cloud"):
        assert w in banned, "'%s' is a subject the owner deprioritised and it is no longer refused" % w


def test_a_real_target_voss_was_refusing_now_passes():
    """Pins the behaviour, not the word list: these are verbatim beliefs from his live backlog."""
    core = literal("_BOARD_CORE")
    import re
    def toks(t):
        return {w for w in re.findall(r"[a-z0-9]+", t.lower()) if len(w) > 3}
    # FULL titles, verbatim. A first cut of this test used the truncated forms printed in a console
    # table and failed -- the matching word sits past the cut. A fixture trimmed for display is not
    # the string the gate sees, and asserting on it tests the trimming.
    beliefs = (
        "Insight: self-refinement plateaus at the critic's competence ceiling, not at excellence - "
        "a decaying critic caps quality well below 1",
        "Hypothesis: winner-take-all reinforcement becomes quality-blind (path dependence, measured)",
        "Our grounding-drop firewall is adaptively defeatable: it beats confidence on non-adaptive "
        "RAG poison but loses its edge past ~32% drop-insensitive poison - the moat is conditional",
    )
    for belief in beliefs:
        assert toks(belief) & core, "still refused: %s" % belief[:70]
